# Generated by Django 5.1.4 on 2025-01-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.FloatField(verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('requires_prescription', models.BooleanField(verbose_name='requires prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy_app.client')),
                ('medicines', models.ManyToManyField(related_name='sales', to='pharmacy_app.medicine')),
            ],
        ),
    ]
