# Generated by Django 5.1.4 on 2025-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.FloatField(verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('requires_prescription', models.BooleanField(verbose_name='requires prescription')),
            ],
        ),
    ]
